#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  (1..4).each do |i|
    config.vm.define "redis#{i}" do |s|
      s.vm.hostname = "redis#{i}"
      s.vm.network "private_network", ip: "192.168.44.1#{i}"
      s.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "256"
      end
    end
    if ARGV[0] == 'up'
      system("ssh-keygen -R 192.168.44.1#{i}")
      system("ssh-keygen -R redis#{i}")
    end
  end
end
